### ISSUE TITLE
Catalyst Repository Take Down Request

### ISSUE THREAD

**Issue by JaydenDev** [VelocityDesign/website#1]
I, Catalyst Maintainer, ask that you please delete VelocityDesign/Catalyst.
You should but cannot be forced to, delete the repository. However, I won't be happy and consequences may happen if all repositories that are and related to the Catalyst project. Delete it, please.

**Comment by JaydenDev** [comment]
btw u can keep ur icon, I'll get it back to you shortly.

**Comment by JaydenDev** [comment]
nevermind, disreguard this post.

**Comment by VelocityDesign** [comment]
Sorry I was on vacation.
